from __future__ import annotations

from ..models import ActionType, RiskLevel
from .models import CapabilityDefinition


def _default_capabilities() -> tuple[CapabilityDefinition, ...]:
    string_target = {"type": "string", "minLength": 1}
    no_params = {"type": "object", "additionalProperties": False, "properties": {}}
    window_params = {
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "hwnd": {"type": "integer"},
            "match_mode": {
                "type": "string",
                "enum": ["auto", "hwnd", "title", "app"],
            },
        },
    }
    window_target_schema = {
        **string_target,
        "description": "Window title, installed app name, or hwnd:<number>.",
    }
    return (
        CapabilityDefinition(
            action_type=ActionType.OPEN_APP,
            title="Open local application",
            description="Open an installed Windows application from app_inventory; focus it if already running.",
            target_schema={
                **string_target,
                "description": "Display name or alias of an installed local app.",
            },
            params_schema={
                "type": "object",
                "additionalProperties": False,
                "properties": {
                    "executable_path": {"type": "string"},
                    "app_inventory_source": {"type": "string"},
                },
            },
            default_risk=RiskLevel.LOW,
            execution_mode="real",
            handler_name="windows.open_app",
            safety_rules=(
                "Must resolve through app_inventory before execution.",
                "Shell-like apps such as PowerShell, cmd, and terminal are blocked.",
            ),
            planner_guidance=("Use exact app_inventory display names when possible.",),
        ),
        CapabilityDefinition(
            action_type=ActionType.FOCUS_APP,
            title="Focus local application",
            description="Bring an already running installed Windows application window to the foreground.",
            target_schema={
                **string_target,
                "description": "Display name or alias of an installed local app.",
            },
            params_schema=no_params,
            default_risk=RiskLevel.LOW,
            execution_mode="real",
            handler_name="windows.focus_app",
            safety_rules=(
                "Must resolve through app_inventory before execution.",
                "Only focuses an existing visible window; it does not launch the app.",
            ),
            planner_guidance=("Use focus_app when the user asks to switch to or return to an app.",),
        ),
        CapabilityDefinition(
            action_type=ActionType.LIST_WINDOWS,
            title="List visible windows",
            description="Inspect current top-level desktop windows and foreground window state without changing them.",
            target_schema={**string_target, "description": "Window scope, usually visible or all."},
            params_schema={
                "type": "object",
                "additionalProperties": False,
                "properties": {
                    "limit": {"type": "integer", "minimum": 1, "maximum": 100},
                },
            },
            default_risk=RiskLevel.LOW,
            execution_mode="real",
            handler_name="windows.list_windows",
            safety_rules=("Read-only desktop state inspection; does not focus, close, or modify windows.",),
            planner_guidance=("Use before focus_app when the user asks what is open or target window state is unclear.",),
        ),
        CapabilityDefinition(
            action_type=ActionType.FOCUS_WINDOW,
            title="Focus window",
            description="Bring a specific existing desktop window to the foreground by title, app name, or hwnd.",
            target_schema=window_target_schema,
            params_schema=window_params,
            default_risk=RiskLevel.LOW,
            execution_mode="real",
            handler_name="windows.focus_window",
            safety_rules=("Only changes foreground focus; does not launch apps or close windows.",),
            planner_guidance=("Use for explicit window-title focus requests or when app_inventory matching is uncertain.",),
        ),
        CapabilityDefinition(
            action_type=ActionType.MINIMIZE_WINDOW,
            title="Minimize window",
            description="Minimize a specific existing desktop window by title, app name, or hwnd.",
            target_schema=window_target_schema,
            params_schema=window_params,
            default_risk=RiskLevel.LOW,
            execution_mode="real",
            handler_name="windows.minimize_window",
            safety_rules=("Only changes window state; does not close or modify app data.",),
            planner_guidance=("Use when the user asks to hide or minimize a window/application.",),
        ),
        CapabilityDefinition(
            action_type=ActionType.MAXIMIZE_WINDOW,
            title="Maximize window",
            description="Maximize a specific existing desktop window by title, app name, or hwnd.",
            target_schema=window_target_schema,
            params_schema=window_params,
            default_risk=RiskLevel.LOW,
            execution_mode="real",
            handler_name="windows.maximize_window",
            safety_rules=("Only changes window state; does not close or modify app data.",),
            planner_guidance=("Use when the user asks to maximize or enlarge a window/application.",),
        ),
        CapabilityDefinition(
            action_type=ActionType.RESTORE_WINDOW,
            title="Restore window",
            description="Restore a minimized or maximized desktop window to normal visible state.",
            target_schema=window_target_schema,
            params_schema=window_params,
            default_risk=RiskLevel.LOW,
            execution_mode="real",
            handler_name="windows.restore_window",
            safety_rules=("Only changes window state; does not close or modify app data.",),
            planner_guidance=("Use when the user asks to restore, show, or unminimize an existing window/application.",),
        ),
        CapabilityDefinition(
            action_type=ActionType.CLOSE_WINDOW,
            title="Close window",
            description="Request a specific desktop window to close by title, app name, or hwnd.",
            target_schema=window_target_schema,
            params_schema=window_params,
            default_risk=RiskLevel.MEDIUM,
            execution_mode="real",
            handler_name="windows.close_window",
            safety_rules=(
                "May trigger unsaved-work prompts or close an application window.",
                "Requires action-level confirmation unless trusted.",
            ),
            planner_guidance=("Use only when the user explicitly asks to close a window/application.",),
        ),
        CapabilityDefinition(
            action_type=ActionType.OPEN_URL,
            title="Open URL",
            description="Open a web URL in the default browser.",
            target_schema={
                **string_target,
                "description": "HTTP or HTTPS URL.",
                "pattern": "^https?://",
            },
            params_schema=no_params,
            default_risk=RiskLevel.LOW,
            execution_mode="real",
            handler_name="windows.open_url",
            safety_rules=("Only http and https URLs are accepted.",),
            planner_guidance=("Use search URLs when the exact domain is uncertain.",),
        ),
        CapabilityDefinition(
            action_type=ActionType.OPEN_PROJECT,
            title="Open project or known folder",
            description="Open a known project or common user folder from projects.json.",
            target_schema={**string_target, "description": "Project name, known folder name, or existing folder path."},
            params_schema={
                "type": "object",
                "additionalProperties": False,
                "properties": {
                    "project_catalog_source": {"type": "string"},
                    "resolved_path": {"type": "string"},
                },
            },
            default_risk=RiskLevel.LOW,
            execution_mode="real",
            handler_name="windows.open_project",
            safety_rules=("Only opens existing folders; never creates, deletes, or modifies files.",),
            planner_guidance=("Use for Desktop, Downloads, Documents, current workspace, and named local projects.",),
        ),
        CapabilityDefinition(
            action_type=ActionType.OPEN_FOLDER,
            title="Open folder",
            description="Open an existing local folder.",
            target_schema={**string_target, "description": "Existing local folder path or Desktop."},
            params_schema=no_params,
            default_risk=RiskLevel.LOW,
            execution_mode="real",
            handler_name="windows.open_folder",
            safety_rules=("Never create, delete, or modify files.",),
        ),
        CapabilityDefinition(
            action_type=ActionType.OPEN_FILE,
            title="Open file",
            description="Open an existing local file.",
            target_schema={**string_target, "description": "Existing local file path."},
            params_schema=no_params,
            default_risk=RiskLevel.LOW,
            execution_mode="real",
            handler_name="windows.open_file",
            safety_rules=("Never create, delete, or modify files.",),
        ),
        CapabilityDefinition(
            action_type=ActionType.ANSWER_QUERY,
            title="Answer information query",
            description="Fetch a direct web-backed answer and return it in the assistant UI.",
            target_schema={**string_target, "description": "Search or information query."},
            params_schema={
                "type": "object",
                "additionalProperties": False,
                "properties": {
                    "source_url": {"type": "string"},
                    "fallback_url": {"type": "string"},
                },
            },
            default_risk=RiskLevel.LOW,
            execution_mode="real",
            handler_name="web.answer_query",
            safety_rules=("Only performs read-only web information lookup.",),
            planner_guidance=("Use this for weather, prices, news, and factual lookups before open_url.",),
        ),
        CapabilityDefinition(
            action_type=ActionType.SHOW_TASKS,
            title="Show tasks",
            description="Show or summarize task items in the assistant UI.",
            target_schema={**string_target, "description": "Task range such as today or this_week."},
            params_schema=no_params,
            default_risk=RiskLevel.LOW,
            execution_mode="real",
            handler_name="todo.show_tasks",
        ),
        CapabilityDefinition(
            action_type=ActionType.RESTORE_WORKSPACE,
            title="Restore workspace",
            description="Restore a previously known workspace layout.",
            target_schema={**string_target, "description": "Workspace name."},
            params_schema=no_params,
            default_risk=RiskLevel.MEDIUM,
            execution_mode="disabled",
            handler_name="",
            safety_rules=("Prototype does not yet perform real workspace restoration.",),
        ),
        CapabilityDefinition(
            action_type=ActionType.CREATE_REMINDER,
            title="Create reminder",
            description="Create a lightweight reminder in the assistant.",
            target_schema={**string_target, "description": "Reminder time or label."},
            params_schema={
                "type": "object",
                "additionalProperties": False,
                "properties": {"minutes": {"type": "integer", "minimum": 1}},
            },
            default_risk=RiskLevel.LOW,
            execution_mode="real",
            handler_name="todo.create_reminder",
        ),
        CapabilityDefinition(
            action_type=ActionType.START_FOCUS_TIMER,
            title="Start focus timer",
            description="Start a focus timer.",
            target_schema={**string_target, "description": "Timer duration such as 25m."},
            params_schema={
                "type": "object",
                "additionalProperties": False,
                "properties": {"minutes": {"type": "integer", "minimum": 1}},
            },
            default_risk=RiskLevel.LOW,
            execution_mode="simulated",
            handler_name="simulated",
        ),
    )
