from __future__ import annotations

from PySide6.QtWidgets import (
    QComboBox,
    QFrame,
    QHeaderView,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QListWidget,
    QPushButton,
    QTableWidget,
    QVBoxLayout,
)


class MainWindowResourceLayoutMixin:
    def _add_recipe_block(self) -> None:
        recipe_block = QFrame()
        recipe_block.setObjectName("splitterSection")
        recipe_block_layout = QVBoxLayout(recipe_block)
        recipe_block_layout.setContentsMargins(0, 0, 0, 0)
        recipe_block_layout.setSpacing(6)
        recipe_header = QHBoxLayout()
        recipe_header.setSpacing(8)
        recipe_title = QLabel("Recipes")
        recipe_title.setObjectName("panelTitle")
        self.recipe_count_label = QLabel("No recipes")
        self.recipe_count_label.setObjectName("subtitle")
        self.refresh_recipe_button = QPushButton("Refresh")
        self.refresh_recipe_button.setObjectName("secondaryButton")
        self.refresh_recipe_button.clicked.connect(self._refresh_recipe_list)
        recipe_header.addWidget(recipe_title)
        recipe_header.addWidget(self.recipe_count_label, stretch=1)
        recipe_header.addWidget(self.refresh_recipe_button)
        recipe_block_layout.addLayout(recipe_header)

        self.recipe_list = QListWidget()
        self.recipe_list.setObjectName("recipeList")
        self.recipe_list.itemClicked.connect(self.load_recipe_detail)
        self.recipe_list.setMinimumHeight(70)
        recipe_block_layout.addWidget(self.recipe_list)

        self.recipe_action_table = QTableWidget(0, 4)
        self.recipe_action_table.setObjectName("recipeActionTable")
        self.recipe_action_table.setHorizontalHeaderLabels(["Action", "Target", "Risk", "Reason"])
        self.recipe_action_table.verticalHeader().setVisible(False)
        self.recipe_action_table.setSelectionBehavior(QTableWidget.SelectionBehavior.SelectRows)
        self.recipe_action_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
        self.recipe_action_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.Stretch)
        self.recipe_action_table.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeMode.ResizeToContents)
        self.recipe_action_table.horizontalHeader().setSectionResizeMode(3, QHeaderView.ResizeMode.Stretch)
        self.recipe_action_table.setMinimumHeight(90)
        recipe_block_layout.addWidget(self.recipe_action_table)

        recipe_actions = QHBoxLayout()
        recipe_actions.setSpacing(6)
        self.load_recipe_button = QPushButton("Load")
        self.load_recipe_button.setObjectName("primaryButton")
        self.load_recipe_button.clicked.connect(self.load_selected_recipe_plan)
        self.edit_recipe_button = QPushButton("Edit")
        self.edit_recipe_button.setObjectName("secondaryButton")
        self.edit_recipe_button.clicked.connect(self.edit_selected_recipe)
        self.delete_recipe_button = QPushButton("Delete")
        self.delete_recipe_button.setObjectName("dangerButton")
        self.delete_recipe_button.clicked.connect(self.delete_selected_recipe)
        self.save_recipe_edits_button = QPushButton("Save Edits")
        self.save_recipe_edits_button.setObjectName("primaryButton")
        self.save_recipe_edits_button.clicked.connect(self.save_recipe_action_edits)
        self.check_recipe_button = QPushButton("Check")
        self.check_recipe_button.setObjectName("secondaryButton")
        self.check_recipe_button.clicked.connect(self.check_selected_recipe)
        self.move_recipe_step_up_button = QPushButton("Up")
        self.move_recipe_step_up_button.setObjectName("secondaryButton")
        self.move_recipe_step_up_button.clicked.connect(lambda: self.move_selected_recipe_step(-1))
        self.move_recipe_step_down_button = QPushButton("Down")
        self.move_recipe_step_down_button.setObjectName("secondaryButton")
        self.move_recipe_step_down_button.clicked.connect(lambda: self.move_selected_recipe_step(1))
        self.delete_recipe_step_button = QPushButton("Delete Step")
        self.delete_recipe_step_button.setObjectName("dangerButton")
        self.delete_recipe_step_button.clicked.connect(self.delete_selected_recipe_step)
        recipe_actions.addWidget(self.load_recipe_button)
        recipe_actions.addWidget(self.edit_recipe_button)
        recipe_actions.addWidget(self.save_recipe_edits_button)
        recipe_actions.addWidget(self.check_recipe_button)
        recipe_actions.addWidget(self.move_recipe_step_up_button)
        recipe_actions.addWidget(self.move_recipe_step_down_button)
        recipe_actions.addWidget(self.delete_recipe_step_button)
        recipe_actions.addWidget(self.delete_recipe_button)
        recipe_block_layout.addLayout(recipe_actions)
        self._set_recipe_buttons(False)
        self.list_splitter.addWidget(recipe_block)

    def _add_project_block(self) -> None:
        project_block = QFrame()
        project_block.setObjectName("splitterSection")
        project_block_layout = QVBoxLayout(project_block)
        project_block_layout.setContentsMargins(0, 0, 0, 0)
        project_block_layout.setSpacing(6)
        project_header = QHBoxLayout()
        project_header.setSpacing(8)
        project_title = QLabel("Projects")
        project_title.setObjectName("panelTitle")
        self.project_count_label = QLabel("Catalog loading")
        self.project_count_label.setObjectName("subtitle")
        self.refresh_project_button = QPushButton("Refresh")
        self.refresh_project_button.setObjectName("secondaryButton")
        self.refresh_project_button.clicked.connect(self._refresh_project_list)
        self.discover_project_button = QPushButton("Discover")
        self.discover_project_button.setObjectName("secondaryButton")
        self.discover_project_button.clicked.connect(self.discover_projects)
        project_header.addWidget(project_title)
        project_header.addWidget(self.project_count_label, stretch=1)
        project_header.addWidget(self.discover_project_button)
        project_header.addWidget(self.refresh_project_button)
        project_block_layout.addLayout(project_header)

        self.project_list = QListWidget()
        self.project_list.setObjectName("projectList")
        self.project_list.itemClicked.connect(self.load_project_detail)
        self.project_list.setMinimumHeight(70)
        project_block_layout.addWidget(self.project_list)

        self.project_name_input = QLineEdit()
        self.project_name_input.setObjectName("projectNameInput")
        self.project_name_input.setPlaceholderText("Project name")
        project_block_layout.addWidget(self.project_name_input)
        self.project_path_input = QLineEdit()
        self.project_path_input.setObjectName("projectPathInput")
        self.project_path_input.setPlaceholderText("Project or folder path")
        project_block_layout.addWidget(self.project_path_input)
        self.project_path_status_label = QLabel("Path: -")
        self.project_path_status_label.setObjectName("subtitle")
        project_block_layout.addWidget(self.project_path_status_label)
        project_edit_row = QHBoxLayout()
        project_edit_row.setSpacing(6)
        self.project_kind_combo = QComboBox()
        self.project_kind_combo.setObjectName("projectKindCombo")
        self.project_kind_combo.addItems(["project", "folder"])
        self.new_project_button = QPushButton("New")
        self.new_project_button.setObjectName("secondaryButton")
        self.new_project_button.clicked.connect(self.new_project_entry)
        self.browse_project_button = QPushButton("Browse")
        self.browse_project_button.setObjectName("secondaryButton")
        self.browse_project_button.clicked.connect(self.browse_project_path)
        self.save_project_button = QPushButton("Save")
        self.save_project_button.setObjectName("primaryButton")
        self.save_project_button.clicked.connect(self.save_selected_project)
        self.open_project_button = QPushButton("Open")
        self.open_project_button.setObjectName("secondaryButton")
        self.open_project_button.clicked.connect(self.open_selected_project)
        self.delete_project_button = QPushButton("Delete")
        self.delete_project_button.setObjectName("dangerButton")
        self.delete_project_button.clicked.connect(self.delete_selected_project)
        project_edit_row.addWidget(self.project_kind_combo)
        project_edit_row.addWidget(self.new_project_button)
        project_edit_row.addWidget(self.browse_project_button)
        project_edit_row.addWidget(self.save_project_button)
        project_edit_row.addWidget(self.open_project_button)
        project_edit_row.addWidget(self.delete_project_button)
        project_block_layout.addLayout(project_edit_row)
        self.project_description_input = QLineEdit()
        self.project_description_input.setObjectName("projectDescriptionInput")
        self.project_description_input.setPlaceholderText("Description")
        project_block_layout.addWidget(self.project_description_input)
        self._set_project_editor_enabled(False)
        self.list_splitter.addWidget(project_block)
