from __future__ import annotations

from PySide6.QtCore import Qt
from PySide6.QtWidgets import (
    QComboBox,
    QFrame,
    QHeaderView,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QListWidget,
    QPushButton,
    QTableWidget,
    QVBoxLayout,
)

from ..models import ActionType


class MainWindowOperationalLayoutMixin:
    def _add_recent_block(self) -> None:
        recent_block = QFrame()
        recent_block.setObjectName("splitterSection")
        recent_block_layout = QVBoxLayout(recent_block)
        recent_block_layout.setContentsMargins(0, 0, 0, 0)
        recent_block_layout.setSpacing(6)
        recent_header = QHBoxLayout()
        recent_header.setSpacing(8)
        recent_title = QLabel("Recent")
        recent_title.setObjectName("panelTitle")
        self.refresh_recent_button = QPushButton("Refresh")
        self.refresh_recent_button.setObjectName("secondaryButton")
        self.refresh_recent_button.clicked.connect(self._refresh_recent_traces)
        recent_header.addWidget(recent_title, stretch=1)
        recent_header.addWidget(self.refresh_recent_button)
        recent_block_layout.addLayout(recent_header)

        self.recent_list = QListWidget()
        self.recent_list.setObjectName("recentList")
        self.recent_list.itemClicked.connect(self.load_recent_trace)
        self.recent_list.setMinimumHeight(70)
        recent_block_layout.addWidget(self.recent_list)
        self.list_splitter.addWidget(recent_block)

    def _add_debug_block(self) -> None:
        debug_block = QFrame()
        debug_block.setObjectName("splitterSection")
        debug_block_layout = QVBoxLayout(debug_block)
        debug_block_layout.setContentsMargins(0, 0, 0, 0)
        debug_block_layout.setSpacing(6)
        debug_header = QHBoxLayout()
        debug_header.setSpacing(8)
        debug_title = QLabel("Debug Runs")
        debug_title.setObjectName("panelTitle")
        self.debug_count_label = QLabel("No trace selected")
        self.debug_count_label.setObjectName("subtitle")
        debug_header.addWidget(debug_title)
        debug_header.addWidget(self.debug_count_label, stretch=1)
        debug_block_layout.addLayout(debug_header)

        self.debug_list = QListWidget()
        self.debug_list.setObjectName("debugList")
        self.debug_list.itemClicked.connect(self.load_debug_snapshot)
        self.debug_list.setMinimumHeight(70)
        debug_block_layout.addWidget(self.debug_list)
        self.list_splitter.addWidget(debug_block)

    def _add_recovery_block(self) -> None:
        recovery_block = QFrame()
        recovery_block.setObjectName("splitterSection")
        recovery_block_layout = QVBoxLayout(recovery_block)
        recovery_block_layout.setContentsMargins(0, 0, 0, 0)
        recovery_block_layout.setSpacing(6)
        recovery_header = QHBoxLayout()
        recovery_header.setSpacing(8)
        recovery_title = QLabel("Recovery")
        recovery_title.setObjectName("panelTitle")
        self.recovery_count_label = QLabel("No recovery events")
        self.recovery_count_label.setObjectName("subtitle")
        self.refresh_recovery_button = QPushButton("Refresh")
        self.refresh_recovery_button.setObjectName("secondaryButton")
        self.refresh_recovery_button.clicked.connect(self._refresh_recovery_events)
        recovery_header.addWidget(recovery_title)
        recovery_header.addWidget(self.recovery_count_label, stretch=1)
        recovery_header.addWidget(self.refresh_recovery_button)
        recovery_block_layout.addLayout(recovery_header)

        self.recovery_list = QListWidget()
        self.recovery_list.setObjectName("recoveryList")
        self.recovery_list.itemClicked.connect(self.load_recovery_event_detail)
        self.recovery_list.setMinimumHeight(70)
        recovery_block_layout.addWidget(self.recovery_list)
        self.list_splitter.addWidget(recovery_block)

    def _add_capability_block(self) -> None:
        capability_block = QFrame()
        capability_block.setObjectName("splitterSection")
        capability_block_layout = QVBoxLayout(capability_block)
        capability_block_layout.setContentsMargins(0, 0, 0, 0)
        capability_block_layout.setSpacing(6)
        capability_header = QHBoxLayout()
        capability_header.setSpacing(8)
        capability_title = QLabel("Capabilities")
        capability_title.setObjectName("panelTitle")
        self.capability_count_label = QLabel("Catalog loading")
        self.capability_count_label.setObjectName("subtitle")
        self.refresh_capability_button = QPushButton("Refresh")
        self.refresh_capability_button.setObjectName("secondaryButton")
        self.refresh_capability_button.clicked.connect(self._refresh_capability_catalog)
        capability_header.addWidget(capability_title)
        capability_header.addWidget(self.capability_count_label, stretch=1)
        capability_header.addWidget(self.refresh_capability_button)
        capability_block_layout.addLayout(capability_header)

        self.capability_list = QListWidget()
        self.capability_list.setObjectName("capabilityList")
        self.capability_list.itemClicked.connect(self.load_capability_detail)
        self.capability_list.setMinimumHeight(70)
        capability_block_layout.addWidget(self.capability_list)

        edit_row = QHBoxLayout()
        edit_row.setSpacing(6)
        self.capability_mode_combo = QComboBox()
        self.capability_mode_combo.setObjectName("capabilityModeCombo")
        self.capability_mode_combo.addItems(["real", "simulated", "disabled"])
        self.capability_risk_combo = QComboBox()
        self.capability_risk_combo.setObjectName("capabilityRiskCombo")
        self.capability_risk_combo.addItems(["low", "medium", "high", "critical"])
        self.save_capability_button = QPushButton("Save")
        self.save_capability_button.setObjectName("primaryButton")
        self.save_capability_button.clicked.connect(self.save_selected_capability)
        edit_row.addWidget(self.capability_mode_combo)
        edit_row.addWidget(self.capability_risk_combo)
        edit_row.addWidget(self.save_capability_button)
        capability_block_layout.addLayout(edit_row)

        self.capability_description_input = QLineEdit()
        self.capability_description_input.setObjectName("capabilityDescriptionInput")
        self.capability_description_input.setPlaceholderText("Capability description")
        capability_block_layout.addWidget(self.capability_description_input)
        self._set_capability_editor_enabled(False)
        self.list_splitter.addWidget(capability_block)

    def _add_window_block(self) -> None:
        window_block = QFrame()
        window_block.setObjectName("splitterSection")
        window_block_layout = QVBoxLayout(window_block)
        window_block_layout.setContentsMargins(0, 0, 0, 0)
        window_block_layout.setSpacing(6)
        window_header = QHBoxLayout()
        window_header.setSpacing(8)
        window_title = QLabel("Windows")
        window_title.setObjectName("panelTitle")
        self.window_count_label = QLabel("Not refreshed")
        self.window_count_label.setObjectName("subtitle")
        self.refresh_windows_button = QPushButton("Refresh")
        self.refresh_windows_button.setObjectName("secondaryButton")
        self.refresh_windows_button.clicked.connect(self._refresh_window_list)
        window_header.addWidget(window_title)
        window_header.addWidget(self.window_count_label, stretch=1)
        window_header.addWidget(self.refresh_windows_button)
        window_block_layout.addLayout(window_header)

        self.window_table = QTableWidget(0, 5)
        self.window_table.setObjectName("windowTable")
        self.window_table.setHorizontalHeaderLabels(["HWND", "Title", "PID", "State", "Exe"])
        self.window_table.verticalHeader().setVisible(False)
        self.window_table.setEditTriggers(QTableWidget.EditTrigger.NoEditTriggers)
        self.window_table.setSelectionBehavior(QTableWidget.SelectionBehavior.SelectRows)
        self.window_table.setSelectionMode(QTableWidget.SelectionMode.SingleSelection)
        self.window_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
        self.window_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.Stretch)
        self.window_table.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeMode.ResizeToContents)
        self.window_table.horizontalHeader().setSectionResizeMode(3, QHeaderView.ResizeMode.ResizeToContents)
        self.window_table.horizontalHeader().setSectionResizeMode(4, QHeaderView.ResizeMode.Stretch)
        self.window_table.setMinimumHeight(90)
        self.window_table.itemSelectionChanged.connect(self.load_selected_window_detail)
        window_block_layout.addWidget(self.window_table)

        window_actions = QHBoxLayout()
        window_actions.setSpacing(6)
        self.focus_window_button = QPushButton("Focus")
        self.focus_window_button.setObjectName("secondaryButton")
        self.focus_window_button.clicked.connect(lambda: self._run_window_action(ActionType.FOCUS_WINDOW))
        self.minimize_window_button = QPushButton("Min")
        self.minimize_window_button.setObjectName("secondaryButton")
        self.minimize_window_button.clicked.connect(lambda: self._run_window_action(ActionType.MINIMIZE_WINDOW))
        self.restore_window_button = QPushButton("Restore")
        self.restore_window_button.setObjectName("secondaryButton")
        self.restore_window_button.clicked.connect(lambda: self._run_window_action(ActionType.RESTORE_WINDOW))
        self.maximize_window_button = QPushButton("Max")
        self.maximize_window_button.setObjectName("secondaryButton")
        self.maximize_window_button.clicked.connect(lambda: self._run_window_action(ActionType.MAXIMIZE_WINDOW))
        self.close_window_button = QPushButton("Close")
        self.close_window_button.setObjectName("dangerButton")
        self.close_window_button.clicked.connect(lambda: self._run_window_action(ActionType.CLOSE_WINDOW))
        window_actions.addWidget(self.focus_window_button)
        window_actions.addWidget(self.minimize_window_button)
        window_actions.addWidget(self.restore_window_button)
        window_actions.addWidget(self.maximize_window_button)
        window_actions.addWidget(self.close_window_button)
        window_block_layout.addLayout(window_actions)
        self._set_window_action_buttons(False)
        self.list_splitter.addWidget(window_block)

    def _add_whitelist_block(self) -> None:
        whitelist_block = QFrame()
        whitelist_block.setObjectName("splitterSection")
        whitelist_block_layout = QVBoxLayout(whitelist_block)
        whitelist_block_layout.setContentsMargins(0, 0, 0, 0)
        whitelist_block_layout.setSpacing(6)
        whitelist_header = QHBoxLayout()
        whitelist_header.setSpacing(8)
        whitelist_title = QLabel("Whitelist")
        whitelist_title.setObjectName("panelTitle")
        self.whitelist_count_label = QLabel("No trusted actions")
        self.whitelist_count_label.setObjectName("subtitle")
        self.refresh_whitelist_button = QPushButton("Refresh")
        self.refresh_whitelist_button.setObjectName("secondaryButton")
        self.refresh_whitelist_button.clicked.connect(self._refresh_trust_list)
        whitelist_header.addWidget(whitelist_title)
        whitelist_header.addWidget(self.whitelist_count_label, stretch=1)
        whitelist_header.addWidget(self.refresh_whitelist_button)
        whitelist_block_layout.addLayout(whitelist_header)

        self.whitelist_list = QListWidget()
        self.whitelist_list.setObjectName("whitelistList")
        self.whitelist_list.itemClicked.connect(self.load_trust_detail)
        self.whitelist_list.setMinimumHeight(70)
        whitelist_block_layout.addWidget(self.whitelist_list)

        self.delete_trust_button = QPushButton("Revoke")
        self.delete_trust_button.setObjectName("dangerButton")
        self.delete_trust_button.clicked.connect(self.delete_selected_trust)
        whitelist_block_layout.addWidget(self.delete_trust_button)
        self._set_trust_buttons(False)
        self.list_splitter.addWidget(whitelist_block)
